version: '3.8'

services:
  backend:
    container_name: Hera-back
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./HeraBack:/app/HeraBack
      - ~/.m2/repository:/root/.m2/repository
    depends_on:
      - db
      - redis

    environment:
      MYSQL_HOST: db
      MONGO_URI : mongodb://mongo:27017/hera
    networks:
      - hera_net
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    networks:
      - hera_net
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: hera
      MONGO_INITDB_ROOT_PASSWORD: root
  redis :
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    networks:
      - hera_net
    ports:
      - "6379:6379"
  frontend:
    container_name: Hera-Frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "81:80"
      - "8082:8082"
    volumes:
      - ./HeraFront:/app/HeraFront
    networks:
      - hera_net
    
    
  scrap:
    container_name: scrap
    build:
      context: .
      dockerfile: Dockerfile.scrap
    restart: unless-stopped
    volumes:
      - ./HeraScrap:/app/HeraScrap
  db:
    container_name: hera-DataBase
    image: mysql:8.0.19
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    networks:
      - hera_net
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: hera
      MYSQL_USER: hera
      MYSQL_ROOT_PASSWORD: hera
      MYSQL_PASSWORD: root
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: unless-stopped
      ports:
        - "2002:80"  # Accéder à phpMyAdmin via http://localhost:2002
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
      networks:
        - hera_net

volumes:
  db_data:
  mongo_data:

networks:
  hera_net:
    driver: bridge