FROM node:18
WORKDIR /app/HeraFront
COPY HeraFront/package.json HeraFront/package-lock.json ./
RUN npm ci
COPY HeraFront/ .
COPY entry.sh /entry.sh
RUN chmod +x /entry.sh
EXPOSE 8082
CMD ["/entry.sh", "frontend"]
