FROM maven:3.9.9
WORKDIR /app/HeraBack
COPY HeraBack/pom.xml ./
RUN mvn dependency:resolve
COPY HeraBack/src ./src
COPY entry.sh /entry.sh
RUN chmod +x /entry.sh
EXPOSE 9090
CMD ["/entry.sh", "backend"]